function [DCDROOP, DCSLACK, DCNOSLACK, PVC, PQC, CONV_BUS, CONVTYPE_DC, ...
    CONVTYPE_AC, PCONV, QCONV, VCONV, RTF, XTF, BF, RCONV, XCONV, ...
    BASEKVC, VCMAX, VCMIN, ICMAX, CONVSTATUS, LOSSA, LOSSB, LOSSCR, ...
    LOSSCI, DROOP, PDCSET, VDCSET, DVDCSET, VMC, VAC, PCCONV, QCCONV, ...
    PCLOSS, VMF, VAF, PFIL, QCONVF, QCCONVF]=idx_convdc


%IDX_CONVDC  Defines constants for named column indices to converter matrix.
%   [DCDROOP, DCSLACK, DCNOSLACK, PVC, PQC, CONV_BUS, CONVTYPE_DC, ...
%   CONVTYPE_AC, PCONV, QCONV, VCONV, RTF, XTF, BF, RCONV, XCONV, ...
%   BASEKVC, VCMAX, VCMIN, ICMAX, CONVSTATUS, LOSSA, LOSSB, LOSSCR, ...
%   LOSSCI, DROOP, PDCSET, VDCSET, DVDCSET, VMC, VAC, PCCONV, QCCONV, ...
%   PCLOSS, VMF, VAF, PFIL, QCONVF, QCCONVF]=idx_convdc
%
%   Some examples of usage, after defining the constants using the line above,
%   are:
%
%    Pg = convdc(4, PCONV);         % get the real power output of convertor 4
%    convdc(:, CONVTYPE_AC) = PVC;  % set all converters in voltage controlling mode
% 
%   The index, name and meaning of each column of the bus matrix is given
%   below:
%
%   columns 1-20 must be included in input matrix (in case file)
%    1  CONV_BUS    converter bus number (dc bus numbering)
%    2  CONVTYPE_DC dc bus type (1 = constant power, 2 = dc slack, 
%                   3 = dc voltage droop)
%    3  CONVTYPE_AC ac bus type (1 = PQ, 2 = PV)
%    4  PCONV       Ps, active power injected in the ac grid (MW)
%    5  QCONV       Qs, reactive power injected in the ac grid (MVAr)
%    6  VCONV       Vtar, target voltage of converter connected ac bus (p.u.)
%    7  RTF       	rtf, transformer resistance (p.u.)
%    8  XTF         xtf, transformer reactance (p.u.)
%    9  BF          bf, filter susceptance (p.u.)
%    10 RCONV       rc, phase reactor resistance (p.u.)
%    11 XCONV       xc, phase reactor reactance (p.u.)
%    12 BASEKVC     converter baseKV, base voltage (kV)
%    13 VCMAX       maxVc, maximum converter voltage magnitude (p.u.)
%    14 VCMIN       minVc, minimum converter voltage magnitude (p.u.)
%    15 ICMAX       Imax, maximum converter current (p.u.)
%    16 CONVSTATUS  converter status (1 = on, 0 = off)
%    17 LOSSA       LossA, constant loss coefficient (MW)
%    18 LOSSB       LossB, linear loss coefficient(kV) 
%    19 LOSSCR      LossCrec, rectifier quadratic loss coefficient (Ohm)
%    20 LOSSCI      LossCinv, inverter quadratic loss coefficient (Ohm)
%
%   columns 21-24 (droop control) can be included in input matrix (in case file)
%    21 DROOP       dc voltage droop (MW/p.u)
%    22 PDCSET      voltage droop power set-point (MW)
%    23 VDCSET      voltage droop voltage set-point (p.u.)
%    24 DVDCSET     voltage droop deadband (p.u.) (optional)
%   
%   columns 25-34 are added to matrix after the power flow solution
%   they are typically not present in the input matrix
%    25 VMC         Vm_C, converter voltage magnitude (p.u.)
%    26 VAC         Va_C, converter voltage angle (degrees)
%    27 PCCONV      Pc, active power generated by the converter (MW)
%    28 QCCONV      Qc, reactive power generated by the converter (MVAr)
%    29 PCLOSS      Pl, active converter power losses (MW)
%    30 VMF         Vm_F, filter voltage magnitude (p.u.)
%    31 VAF         Va_F, filter voltage angle (degrees)
%    32 PFIL        Psf or Pcf, active power at filter bus (MW)
%    33 QCONVF      Qsf, reactive power through transformer at filter bus (MVAr)
%    34 QCCONVF     Qcf, reactive power through reactor at filter bus (MVAr)
% 
%   additional constants, used to assign/compare values in the CONVTYPE_DC 
%   and CONVTYPE_AC column
%    3  DCDROOP     dc voltage droop
%    2  DCSLACK     dc slack bus
%    1  DCNOSLACK   constant active power bus    
%    2  PVC         constant voltage converter control
%    1  PQC         constant reactive power converter control

%   MatACDC
%   Copyright (C) 2012 Jef Beerten
%   University of Leuven (KU Leuven)
%   Dept. Electrical Engineering (ESAT), Div. ELECTA
%   Kasteelpark Arenberg 10
%   3001 Leuven-Heverlee, Belgium

%% define bus types
DCDROOP     = 3;    %% dc voltage droop 
DCSLACK     = 2;    %% dc slack bus
DCNOSLACK   = 1;    %% constant active power slack bus
PVC         = 2;    %% constant voltage converter control
PQC         = 1;    %% constant reactive power converter control


%% define the indices
CONV_BUS    = 1;    %% converter bus number (dc bus numbering)
CONVTYPE_DC = 2;    %% dc bus type (1 = constant power, 2 = dc slack)
CONVTYPE_AC = 3;    %% ac bus type (1 = PQ, 2 = PV)
PCONV       = 4;    %% P, active power injected in the ac grid (MW)
QCONV       = 5;    %% Q, reactive power injected in the ac grid (MVAr)
VCONV       = 6;    %% Vtar, target voltage of converter connected ac bus (p.u.)
RTF         = 7;    %% rtf, transformer resistance (p.u.)
XTF         = 8;    %% xtf, transformer reactance (p.u.)
BF          = 9;    %% bf, filter susceptance (p.u.)
RCONV       = 10;   %% rc, phase reactor resistance (p.u.)
XCONV       = 11;   %% xc, phase reactor reactance (p.u.)
BASEKVC     = 12;   %% converter baseKV, base voltage (kV)
VCMAX       = 13;   %% maxVc, maximum converter voltage magnitude (p.u.)
VCMIN       = 14;   %% minVc, minimum converter voltage magnitude (p.u.)
ICMAX       = 15;   %% Imax, maximum converter current (p.u.)
CONVSTATUS  = 16;   %% converter status (1 = on, 0 = off)
LOSSA       = 17;   %% LossA, constant loss coefficient  (MW)
LOSSB       = 18;   %% LossB, linear loss coefficient    (kV) 
LOSSCR      = 19;   %% LossCrec, rectifier quadratic loss coefficient (Ohm)
LOSSCI      = 20;   %% LossCinv, inverter quadratic loss coefficient (Ohm)

%% columns only have to be included when a voltage droop operation is
%% considered
DROOP       = 21;       %% dc voltage droop (p.u/MW)
PDCSET      = 22;       %% voltage droop power set-point (MW)
VDCSET      = 23;       %% voltage droop voltage set-point (p.u.)
DVDCSET     = 24;       %% voltage droop deadband (p.u.)

%% included in pf solution, not necessarily in input
VMC         = 25;   %% Vm_C, converter voltage magnitude (p.u.)
VAC         = 26;   %% Va_C, converter voltage angle (degrees)
PCCONV      = 27;   %% Pc, active power generated by the converter (MW)
QCCONV      = 28;   %% Qc, reactive power generated by the converter (MVAr)
PCLOSS      = 29;   %% Pl, active converter power losses (MW)
VMF         = 30;   %% Vm_F, filter voltage magnitude (p.u.)
VAF         = 31;   %% Va_F, filter voltage angle (degrees)
PFIL        = 32;   %% Psf or Pcf, active power at filter bus (MW)
QCONVF      = 33;   %% Qsf, reactive power through transformer at filter bus (MVAr)
QCCONVF     = 34;   %% Qcf, reactive power through reactor at filter bus (MVAr)

return;
